# CLASE 07 Creación de Arrays
## Prof. Andrés Mena Abarca
### Estudiante: Eric Ricardo Padilla Mora 

### Crear un array a partir de una lista

In [3]:
import numpy as np

lista = [1, 2, 3, 4, 5]

# Convertir la lista a un array
array = np.array(lista)

print(array)


[1 2 3 4 5]


### Crear un array de ceros de tamaño 5x5

In [26]:
#Código crear un array de ceros de tamaño 5x5
array_ceros = np.zeros((3, 3))

print(array_ceros)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Crear un array de unos de tamaño 3x3

In [31]:
#Código crear un array de unos de tamaño 3x3
# Crear un array de unos de tamaño 5x5
array_unos = np.ones((5, 4))

print(array_unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Crear un array con valores espaciados uniformemente de 0 a 9

In [32]:
#Código rear un array con valores espaciados uniformemente de 0 a 9
array_linear = np.linspace(0, 9, 10)

print(array_linear)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [113]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1
array_reto = np.linspace(0, 1, 100)

print(array_reto)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [42]:
array_salario = np.array([50,40,20])
array_propinas = np.array([6,4,9])

#Código realizar una suma, resta, multiplicación y división entre dos arrays
suma = array_salario + array_propinas
resta = array_salario - array_propinas
multiplicacion = array_salario * array_propinas
division = array_salario / array_propinas
# Salida
'''
print("La suma es: ",suma)
#print("La resta es: ",resta)
#print("La multiplicación es: ",multiplicacion)
#print("La división es: ",division)
'''
print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicación es: ",multiplicacion)
print("La división es: ",division)

La suma es:  [56 44 29]
La resta es:  [44 36 11]
La multiplicación es:  [300 160 180]
La división es:  [ 8.33333333 10.          2.22222222]


In [70]:
#Calcular el producto punto de dos arrays
multiplicacion = np.dot(array_salario,array_propinas)
print(f'El producto escalar salarios con propinas da: {multiplicacion}')

El producto escalar salarios con propinas da: 640


In [76]:
vector_columna = np.array([[1], [2], [3]])

# Transponer el vector columna
transpuesta_columna = vector_columna.T

print("Vector columna original:")
print(vector_columna)

print("\nVector columna transpuesto:")
print(transpuesta_columna)

Vector columna original:
[[1]
 [2]
 [3]]

Vector columna transpuesto:
[[1 2 3]]


# Operaciones Estadísticas

In [114]:
#Calcular la media, suma, valor mínimo y valor máximo de un array


# Crear un array NumPy
array_numeros = np.array([5, 2, 4, 1, 3])

# Calcular la media
array_original = np.array([1, 2, 3, 4, 5, 6])

media =np.mean(array_original)
print(f'El promedio de los datos es: {media}')
# Calcular la suma
suma = np.sum(array_original)
print(f'La suma es de los datos es: {suma}')

# Calcular el valor mínimo
minimo = np.min(array_original)
print(f'El mínimo de los datos es: {minimo}')

# Calcular el valor máximo
maximo = np.max(array_original)
print(f'El máximo de los datos es: {maximo}')
'''
# Mostrar los resultados
print("La media es:", media)
print("La suma es:", suma)
print("El valor mínimo es:", valor_minimo)
print("El valor máximo es:", valor_maximo)
'''


El promedio de los datos es: 3.5
La suma es de los datos es: 21
El mínimo de los datos es: 1
El máximo de los datos es: 6


'\n# Mostrar los resultados\nprint("La media es:", media)\nprint("La suma es:", suma)\nprint("El valor mínimo es:", valor_minimo)\nprint("El valor máximo es:", valor_maximo)\n'

In [115]:

# Crear un array original
array_original = np.array([1, 2, 3, 4, 5, 6])


# Nueva forma deseada (2 filas y 3 columnas)
array_reshapeado = array_original.reshape(3,2)
print(array_reshapeado)

# Crear un array original

# Nueva forma deseada (2 filas y 3 columnas)


'''
# Imprimir el array original y el reshapeado
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)
'''

[[1 2]
 [3 4]
 [5 6]]


'\n# Imprimir el array original y el reshapeado\nprint("Array original:", array_original)\nprint("Array reshapeado:", array_reshapeado)\n'

# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [118]:
nuevo_array = np.array([[1,2],[2,5]])
print(f'La matriz es:\n {nuevo_array}')
#Código para calcular el determinante de una matriz 2x2
determinante = np.linalg.det(nuevo_array)
#print(determinante)}
print(f'El valor del determinante de la matriz es {determinante}')

La matriz es:
 [[1 2]
 [2 5]]
El valor del determinante de la matriz es 1.0


### Calcular la matriz inversa de una matriz 3x3

In [ ]:
# Definir la matriz 3x3
nueva_matriz = np.array([[12,2,15],[2,45,4],[6,7,8]])
print(f'La matriz es:\n {nueva_matriz}')
#Cálculo del determinante para ver que tenga inversa
# determinante = np.linalg.det(nueva_matriz)

inversa = np.linalg.inv(nueva_matriz)

# Mostrar la inversa

print("\nLa matriz inversa es:\n")
print(inversa)

# Imprimir la matriz inversa



La matriz es:
 [[12  2 15]
 [ 2 45  4]
 [ 6  7  8]]
El valor del determinante de la matriz es 160.000

La matriz inversa es:

[[ 2.075    0.55625 -4.16875]
 [ 0.05     0.0375  -0.1125 ]
 [-1.6     -0.45     3.35   ]]


### Calcular los valores propios y vectores propios de una matriz 4x4

In [130]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Calcular valores propios y vectores propios
valores_propios, vectores_propios = np.linalg.eig(matriz_4x4)

# Mostrar los resultados
print("Los valores propios son:\n", valores_propios)
print("Los vectores propios son:\n")
print(vectores_propios)

# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
'''
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])
'''

Los valores propios son:
 [ 3.62093727e+01 -2.20937271e+00 -2.62410379e-15 -9.51420961e-17]
Los vectores propios son:

[[-0.15115432 -0.72704996 -0.47688035 -0.07702174]
 [-0.34923733 -0.28320876  0.83665151 -0.30149603]
 [-0.54732033  0.16063243 -0.24266197  0.83405728]
 [-0.74540333  0.60447363 -0.11710919 -0.45553951]]


'\nprint("Valores propios:", autovalores)\nprint("Vectores propios:")\nfor i in range(len(autovectores)):\n    print(f"Vector propio {i+1}:", autovectores[i])\n'

# Funciones Universales

In [136]:
import math
# Crear un array con ángulos
array_angulos = np.array([0, np.pi/2, np.pi])

# Calcular el seno de cada ángulo
seno_angulos = np.sin(array_angulos)

# Mostrar el resultado
print("El seno de los ángulos es:", seno_angulos)

# Calcular el coseno de los ángulos
cos_angulos = np.sin(array_angulos)

# Mostrar el resultado
print("El coseno de los ángulos es:", cos_angulos)

# Calcular la exponencial de los ángulos
# Definir un array de ángulos en radianes
array_angulos = np.array([0, np.pi/2, np.pi])

# Calcular la exponencial de cada ángulo
exp_angulos = np.exp(array_angulos)

# Mostrar el resultado
print("La exponencial de los ángulos es:", exp_angulos)


# Definir el arreglo de los ángulos en radianes
array_angulos = np.array([0.1, np.pi/2, np.pi])  # Usamos 0.1 para evitar log(0)

# Calcular el logaritmo natural de cada ángulo
log_angulos = np.log(array_angulos)

print("El logaritmo de los ángulos es:", log_angulos)


El seno de los ángulos es: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
El coseno de los ángulos es: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
La exponencial de los ángulos es: [ 1.          4.81047738 23.14069263]
El logaritmo de los ángulos es: [-2.30258509  0.45158271  1.14472989]


In [142]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Obtener la primera fila del array
# Obtener la primera fila
primera_fila = array_2d[0]

# Mostrar la primera fila
print("La primera fila es:", primera_fila)

# Obtener la última columna del array
  # [3, 6, 9]
# Obtener la primera fila
ultima_columna = array_2d[ :, -1]

# Mostrar la primera fila
print("La última columna es:", ultima_columna)
# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]
submatriz = array_2d[1:2, :2]

# Imprimir los subconjuntos de datos extraídos
print("La submatriz es:")
print(submatriz)

La primera fila es: [1 2 3]
La última columna es: [3 6 9]
La submatriz es:
[[4 5]]


# Generación de Números Aleatorios

In [144]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100
# Generar un número aleatorio entre 0 y 100 (sin incluir 100)
numero_aleatorio = np.random.randint(1, 101, 10)

# Mostrar el resultado
print("Número aleatorio entre 1 y 100:", numero_aleatorio)

Número aleatorio entre 1 y 100: [14 84 79 22 69 83 98 20 28 44]


In [147]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1
matriz_aleatoria = np.random.rand(2, 3)

# Mostrar la matriz
print("Matriz 2x3 con números aleatorios entre 0 y 1:")
print(matriz_aleatoria)

Matriz 2x3 con números aleatorios entre 0 y 1:
[[0.57874098 0.787703   0.20993801]
 [0.968983   0.66310958 0.18359768]]


In [148]:
# Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)
array_normal = np.random.randn(5)

# Mostrar el array
print("Array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1):")
print(array_normal)


Array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1):
[ 2.20619379 -0.54619362 -1.58730286 -0.6240477   0.05256075]


# Ejercicios Reales o prácticos

## Caso 1. Preferencias de Mariana

In [68]:
# Preferencias Mariana (Acción, Comedia, Drama)

mariana = np.array([7,9,2])
avatar = np.array([10,1,5]) # más acción menos comedia
brave_heart = np.array([8,1,7]) # más acción menos comedia

# Calcular la similtud de estas películas con los gustos de Mariana
similitud_p1 = np.dot(mariana,avatar)
similitud_p2 = np.dot(mariana,brave_heart)

print(f'La similitud de preferencias de Mariana con avatar es de: {similitud_p1}')
print(f'La similitud de preferencias de Mariana con brave heart es de: {similitud_p2}')
if similitud_p1 > similitud_p2:
     print('Le recomendamos avatar')
else:
    print('Le recomendamos brave heart')

La similitud de preferencias de Mariana con avatar es de: 89
La similitud de preferencias de Mariana con brave heart es de: 79
Le recomendamos avatar


## Caso 2. Estudio de correlación

In [86]:
import numpy as np
#Datos Tipo Cambio Dolar Ultimos 10 meses | IPC , metrica mesual


tipo_cambio = np.array([506.96,505.00,504.27,505.52,506.23,506.23,506.23,506.58,506.87,507.25])
ipc = np.array([109.46,109.55,109.71,109.57,109.70,109.33,108.85, 109.36,110.39,110.79])


#Calcular coeficiente de correlación
correlacion = np.corrcoef(tipo_cambio,ipc)[0,1]


print(f'Coeficiente de correlación: {correlacion:.4f}')

Coeficiente de correlación: 0.3208


## Caso 3. Horas de Estudio vrs Notas

In [112]:
horas_estudio = np.array([1,2,3,4,5,6,7,8,9,10]) #Horas de estudio
notas = np.array([50,55,60,63,67,72,75,78,81,85]) #Notas obtenidas

#Cálculo crecimiento del promedio del puntaje por horas de estudio

diferencia_notas = np.diff(notas)
promedio = np.mean(diferencia_notas)
 
promedio_pond =  np.average([[50,75,90],[10,75,15]])
print(f'Promedio ponderado: {promedio_pond}')
print(f'La diferencia de las notas es: {diferencia_notas}')
print(f'El promedio del incremento por cada hora de estudio corresponde a: {promedio:.3f}')

# Estimación dedel puntaje si estudio 12 horas
proyeccion_estudio = 12
nota_estimada = (proyeccion_estudio - horas_estudio[-1])*promedio + max(notas)
nota_min = (min(horas_estudio) - proyeccion_estudio)*promedio + min(notas)

print(f'La nota máxima estimada si estudio {proyeccion_estudio} es de: {nota_estimada:.3f}')
print(f'La nota mínima estimada si estudio {proyeccion_estudio} es de: {nota_min:.3f}')

Promedio ponderado: 52.5
La diferencia de las notas es: [5 5 3 4 5 3 3 3 4]
El promedio del incremento por cada hora de estudio corresponde a: 3.889
La nota máxima estimada si estudio 12 es de: 92.778
La nota mínima estimada si estudio 12 es de: 7.222
